<#
.SYNOPSIS
    Helpers for the Cluster Announcer service: generate the announcer
    PowerShell script that hosts the /.well-known/cluster-controller
    JSON endpoint, and build the JSON payload that endpoint serves.

.DESCRIPTION
    The Announcer is a tiny HTTP listener (HttpListener-based; no Node
    dependency, no extra service framework) installed via NSSM in Stage 23.

    On the host side, lib/Discovery.psm1 hits
       http://<candidate>:8765/.well-known/cluster-controller
    and looks for a JSON body whose `type` field equals `cluster-controller`,
    matching the contract this module emits.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function New-AnnouncerPayload {
    <#
    .SYNOPSIS
        Build the JSON object that the announcer endpoint serves. Returns
        a pscustomobject; caller pipes it to ConvertTo-Json.

    .PARAMETER Hostname     Controller's announced hostname (controller.lan).
    .PARAMETER LanIp        Optional explicit LAN IP. Default null -> hosts
                            resolve via DNS.
    .PARAMETER HttpsPort    443 by default.
    .PARAMETER AgentPort    4433 by default (set equal to HttpsPort when
                            agents_port_same_as_https=true).
    .PARAMETER Version      Controller setup version stamp (semver).
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Hostname,
        [string]$LanIp,
        [int]$HttpsPort = 443,
        [int]$AgentPort = 4433,
        [string]$Version = '0.1.0'
    )
    [pscustomobject]@{
        type        = 'cluster-controller'
        version     = $Version
        hostname    = $Hostname
        lan_ip      = $LanIp
        https_port  = $HttpsPort
        agent_port  = $AgentPort
        emitted_at  = [datetime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ss.fffZ')
    }
}

function Get-AnnouncerScriptContent {
    <#
    .SYNOPSIS
        Return the source text for the standalone announcer script. The
        Announcer stage drops this into %ProgramData%\ClusterController\
        bin\announcer.ps1 and registers it as a Windows service via NSSM.

    .PARAMETER Port    Port to bind. Default 8765.
    .PARAMETER PayloadFile JSON file the listener will serve as the body.

    .DESCRIPTION
        Returned script is deliberately minimal: no external modules, only
        in-box System.Net.HttpListener. It refuses to bind anything but
        loopback + LAN IPs (rejects 0.0.0.0 to keep traffic on the LAN).
    #>
    [CmdletBinding()]
    param(
        [int]$Port = 8765,
        [Parameter(Mandatory)][string]$PayloadFile
    )
    $escPayload = $PayloadFile -replace "'","''"
    return @"
# AUTO-GENERATED by windows-cluster-controller (lib/Announce.psm1). DO NOT EDIT.
# Tiny HTTP responder for /.well-known/cluster-controller -> JSON payload file.
# Bound to http://+:$Port/ (HttpListener wildcard).

`$ErrorActionPreference = 'Stop'
`$payloadPath = '$escPayload'
`$listener = [System.Net.HttpListener]::new()
`$listener.Prefixes.Add('http://+:$Port/.well-known/cluster-controller/')
`$listener.Prefixes.Add('http://+:$Port/')
`$listener.Start()
while (`$listener.IsListening) {
    try {
        `$ctx = `$listener.GetContext()
        `$req = `$ctx.Request
        `$resp = `$ctx.Response
        if (`$req.HttpMethod -ne 'GET') {
            `$resp.StatusCode = 405; `$resp.Close(); continue
        }
        if (Test-Path -LiteralPath `$payloadPath) {
            `$body = [System.IO.File]::ReadAllBytes(`$payloadPath)
            `$resp.ContentType = 'application/json'
            `$resp.StatusCode = 200
            `$resp.ContentLength64 = `$body.Length
            `$resp.OutputStream.Write(`$body, 0, `$body.Length)
        } else {
            `$resp.StatusCode = 503
            `$msg = [System.Text.Encoding]::UTF8.GetBytes('payload not ready')
            `$resp.OutputStream.Write(`$msg, 0, `$msg.Length)
        }
        `$resp.Close()
    } catch {
        # Don't crash on transient errors; keep listening.
        Start-Sleep -Milliseconds 50
    }
}
"@
}

Export-ModuleMember -Function `
    New-AnnouncerPayload, Get-AnnouncerScriptContent
