<#
.SYNOPSIS
    Stage 5 -- Database. NeDB (default, no install) or MongoDB (download +
    install + configure + start).

.DESCRIPTION
    Routes on $Config.db.mode:
      * nedb     -- no install. MeshCentral uses its built-in file-backed
                    NeDB. Stage returns Pass with a Skipped step.
      * mongodb  -- full install:
            1. Test-PkgInstalled (registry probe by 'MongoDB Server' regex).
            2. Get-PkgDownload (SHA256-verified MSI).
            3. Install-PkgMsi (msiexec /qn).
            4. Write mongod.cfg (bind 127.0.0.1 -- never expose).
            5. Configure + start the MongoDB Windows service.
            6. Verify TCP 27017 listening on loopback.

    The loopback-only bind is intentional and matches REVIEW_PROMPT.md's
    security guidance: MeshCentral runs on the same machine and connects
    over loopback; MongoDB is never reachable from the LAN.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$libDir = Join-Path (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)) 'src\lib'
foreach ($mod in 'Logging','Pkg','Service','Net','Config','Retry') {
    if (-not (Get-Module -Name $mod)) {
        $candidate = Join-Path $libDir "$mod.psm1"
        if (Test-Path -LiteralPath $candidate) { Import-Module -Name $candidate -Force }
    }
}

# ---------- invoker seam ----------

function Get-DefaultDbInvoker {
    @{
        # Write a mongod.cfg to $Path. Caller pre-renders the body string.
        WriteMongoConfig = {
            param([string]$Path, [string]$Body)
            $dir = Split-Path -Parent $Path
            if ($dir -and -not (Test-Path -LiteralPath $dir)) {
                New-Item -Path $dir -ItemType Directory -Force | Out-Null
            }
            [System.IO.File]::WriteAllText($Path, $Body, [System.Text.UTF8Encoding]::new($false))
        }
        EnsureDir = {
            param([string]$Path)
            if (-not (Test-Path -LiteralPath $Path)) {
                New-Item -Path $Path -ItemType Directory -Force | Out-Null
            }
        }
    }
}

$script:DbInvokers = Get-DefaultDbInvoker

function Confirm-DbTestSeamAllowed {
    if (-not $env:CLUSTERCTRL_ALLOW_TEST_SEAMS) {
        throw "Test seams are disabled in production. Set `$env:CLUSTERCTRL_ALLOW_TEST_SEAMS=1 to enable Set-DbInvoker."
    }
}

function Set-DbInvoker {
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseShouldProcessForStateChangingFunctions','',Justification='Test seam gated by env var.')]
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [ValidateSet('WriteMongoConfig','EnsureDir')]
        [string]$Name,
        [Parameter(Mandatory)][scriptblock]$ScriptBlock
    )
    Confirm-DbTestSeamAllowed
    $script:DbInvokers[$Name] = $ScriptBlock
}

function Reset-DbInvoker {
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseShouldProcessForStateChangingFunctions','',Justification='Test seam gated by env var.')]
    [CmdletBinding()]
    param()
    Confirm-DbTestSeamAllowed
    $script:DbInvokers = Get-DefaultDbInvoker
}

# ---------- helpers ----------

function Format-MongoConfig {
    param(
        [Parameter(Mandatory)][string]$BindIp,
        [Parameter(Mandatory)][int]$Port,
        [Parameter(Mandatory)][string]$DataDir,
        [Parameter(Mandatory)][string]$LogDir
    )
    @"
# AUTO-GENERATED by windows-cluster-controller stages/05-Db.ps1. Do not edit by hand.
storage:
  dbPath: $DataDir
  journal:
    enabled: true

systemLog:
  destination: file
  logAppend: true
  path: $LogDir/mongod.log

net:
  bindIp: $BindIp
  port: $Port

setParameter:
  enableLocalhostAuthBypass: false
"@
}

# ---------- public ----------

function Invoke-DbStage {
    <#
    .SYNOPSIS  Provision the MeshCentral database backend (NeDB or MongoDB).
    .PARAMETER Config       Parsed cluster-controller.json pscustomobject.
    .PARAMETER MongoMsiUrl  Required if db.mode=mongodb.
    .PARAMETER MongoMsiSha256 Required if db.mode=mongodb.
    .PARAMETER DryRun       Skip mutating calls; report decisions.
    #>
    [CmdletBinding()]
    param(
        $Config,
        [string]$MongoMsiUrl,
        [string]$MongoMsiSha256,
        [switch]$DryRun
    )

    $steps = New-Object System.Collections.Generic.List[object]
    function _step($n,$s,$d) { $steps.Add([pscustomobject]@{ Name = $n; Status = $s; Detail = $d }) }

    # Resolve config fields with defaults so the stage can run with empty -Config.
    $mode    = 'nedb'
    $bind    = '127.0.0.1'
    $port    = 27017
    $dataDir = (Join-Path $env:ProgramData 'ClusterController\mongo\data')
    $logDir  = (Join-Path $env:ProgramData 'ClusterController\mongo\log')
    if ($Config -and $Config.PSObject.Properties['db'] -and $Config.db) {
        if ($Config.db.PSObject.Properties['mode']) { $mode = "$($Config.db.mode)" }
        if ($Config.db.PSObject.Properties['mongodb'] -and $Config.db.mongodb) {
            $m = $Config.db.mongodb
            if ($m.PSObject.Properties['bind'])     { $bind    = "$($m.bind)" }
            if ($m.PSObject.Properties['port'])     { $port    = [int]$m.port }
            if ($m.PSObject.Properties['data_dir']) { $dataDir = (Expand-ConfigPath -Value "$($m.data_dir)") }
            if ($m.PSObject.Properties['log_dir'])  { $logDir  = (Expand-ConfigPath -Value "$($m.log_dir)") }
        }
    }

    _step 'Resolve db.mode' 'Pass' "mode=$mode (bind=$bind port=$port)"

    if ($mode -eq 'nedb') {
        _step 'Skip MongoDB install' 'Pass' 'db.mode=nedb -- MeshCentral built-in NeDB will be used; no MongoDB install required.'
        return [pscustomobject]@{ Overall = 'Pass'; Steps = $steps.ToArray(); Detail = 'NeDB mode: no DB install' }
    }
    if ($mode -ne 'mongodb') {
        _step 'Resolve db.mode' 'Fail' "unsupported db.mode '$mode' (must be 'nedb' or 'mongodb')"
        return [pscustomobject]@{
            Overall     = 'Fail'
            Steps       = $steps.ToArray()
            Detail      = "unsupported db.mode '$mode'"
            Remediation = 'Set cluster-controller.json db.mode to either "nedb" or "mongodb".'
        }
    }

    # ---- MongoDB path ----

    # Idempotency: is MongoDB already installed?
    $probe = Test-PkgInstalled -NameRegex '^MongoDB.*Server'
    $alreadyInstalled = $probe.Found

    if ($alreadyInstalled) {
        _step 'Detect existing MongoDB' 'Pass' "$($probe.DisplayName) $($probe.DisplayVersion) already installed"
    } else {
        _step 'Detect existing MongoDB' 'Warn' 'MongoDB not installed -- proceeding to install'
    }

    if ($DryRun) {
        _step 'Install/configure MongoDB' 'Skipped' '-DryRun: skipping mutations'
        return [pscustomobject]@{ Overall = 'Pass'; Steps = $steps.ToArray(); Detail = 'DryRun: MongoDB install path' }
    }

    if (-not $alreadyInstalled) {
        if (-not $MongoMsiUrl) {
            _step 'Install MongoDB' 'Fail' 'db.mode=mongodb but no -MongoMsiUrl supplied'
            return [pscustomobject]@{
                Overall     = 'Fail'
                Steps       = $steps.ToArray()
                Detail      = 'MongoDB MSI URL missing'
                Remediation = 'Pass -MongoMsiUrl + -MongoMsiSha256 for the desired MongoDB Community Server MSI, or set db.mode=nedb.'
            }
        }
        $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ('mongo-' + [guid]::NewGuid().ToString('N').Substring(0,8) + '.msi')
        $dl  = Get-PkgDownload -Url $MongoMsiUrl -Dest $tmp -Sha256 $MongoMsiSha256
        if (-not $dl.Ok) {
            _step 'Download MongoDB MSI' 'Fail' $dl.Detail
            return [pscustomobject]@{ Overall = 'Fail'; Steps = $steps.ToArray(); Detail = "MongoDB MSI download failed: $($dl.Detail)" }
        }
        _step 'Download MongoDB MSI' 'Pass' $dl.Detail
        $ins = Install-PkgMsi -MsiPath $tmp
        Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue
        if (-not $ins.Ok) {
            _step 'Install MongoDB MSI' 'Fail' $ins.Detail
            return [pscustomobject]@{ Overall = 'Fail'; Steps = $steps.ToArray(); Detail = "msiexec exited $($ins.ExitCode)" }
        }
        _step 'Install MongoDB MSI' 'Pass' $ins.Detail
    }

    # Create data + log dirs.
    & $script:DbInvokers.EnsureDir $dataDir
    & $script:DbInvokers.EnsureDir $logDir
    _step 'Ensure data + log dirs' 'Pass' "data=$dataDir; log=$logDir"

    # Write mongod.cfg (deterministic).
    $cfgPath = Join-Path $logDir 'mongod.cfg'
    $cfgPath = Join-Path (Split-Path -Parent $dataDir) 'mongod.cfg'
    $body = Format-MongoConfig -BindIp $bind -Port $port -DataDir $dataDir -LogDir $logDir
    & $script:DbInvokers.WriteMongoConfig $cfgPath $body
    _step 'Write mongod.cfg' 'Pass' "config=$cfgPath bind=$bind"

    # Configure + start the MongoDB service.
    $svcName = 'MongoDB'
    $startResult = Set-ServiceStartType -Name $svcName -StartType 'Automatic'
    if ($startResult.Ok) {
        _step 'Service startup type' 'Pass' $startResult.Detail
    } else {
        _step 'Service startup type' 'Warn' $startResult.Detail
    }
    $svc = Start-ServiceIdempotent -Name $svcName -WaitSeconds 60
    if ($svc.Ok -and $svc.State -eq 'Running') {
        _step 'Start MongoDB service' 'Pass' $svc.Detail
    } else {
        _step 'Start MongoDB service' 'Fail' $svc.Detail
        return [pscustomobject]@{
            Overall     = 'Fail'
            Steps       = $steps.ToArray()
            Detail      = "MongoDB service did not reach Running state: $($svc.Detail)"
            Remediation = "Inspect log under $logDir for startup errors; run 'Get-Service MongoDB' and 'Start-Service MongoDB' manually."
        }
    }

    # Verify TCP port listening on loopback.
    Start-Sleep -Milliseconds 250   # tiny grace period
    if (Test-NetPortInUse -Port $port -Address $bind -TimeoutMs 1000) {
        _step 'Verify MongoDB listening' 'Pass' "${bind}:${port} accepting connections"
    } else {
        _step 'Verify MongoDB listening' 'Warn' "${bind}:${port} did not respond yet; service is Running -- may still be initialising"
    }

    [pscustomobject]@{
        Overall = 'Pass'
        Steps   = $steps.ToArray()
        Detail  = "MongoDB Running on ${bind}:${port}"
    }
}
